* Praktisk info
- Plats: Spelinkubatorn, Lindholmen
- Tid: Kl 19 - 21, onsdagar.
- Start: 7 september

* Upplägg
- Varje tillfälle börjar med en liten presentation av de spel vi ska studera (oftast 3 - 5 st)
- Deltagarna delar upp sig och försöker hinna spela alla spel (de flesta kommer vara rätt korta)
- Vill man experimentera med egna regelvariationer eller nya spel uppmuntras detta
- Mot slutet samlas vi och diskuterar våra upplevelser, styrkor/svagheter med spelen, etc, etc.

* Planerade tillfällen

** Ett halvt ark papper
Spel som endast kräver papper och penna.

- Sprouts
- Cutting Corners
- Hold that line

** Kort, kort, kort
Ovanliga spel med en vanlig kortlek.

- GOPS
- Mate
- Myre

** Schackbräde utan Schack
Ett gäng underliga spel som spelas på 8 x 8 rutor.

- Focus
- Lines of Action 
- Knight Chase
- Ironclad
- Domain

** För eremiten
Brädspel och kortspel som spelas ensam, mot spelet.

** Digital kartong
Vi tittar närmare på ett gäng brädspel designade specifikt för lokal multiplayer på iPad (ej digitala portningar av befintliga spel).

- Chesh
- Glitch Tank

** Asiatiska delikatesser
- Hanafudakort
- Mahjong
- Go

** Uråldrigheter
Väldigt gamla spel.

- Hnefatafl
- Det kungliga spelet från Ur

** Tärningsspel
...som inte suger

- Qwixx
- 10000
- Liar's Dice

** Göra stan
Spel som spelas med saker man hittar vid bardisken eller på restaurangbordet.

- Flip!
- Skulls
- Hetsjakt

* Möjliga teman för framtiden

** Rollspel från 2000-talet
T.ex. Fiasco

** Twine
Avantgardistiska textäventyr

** BYOG
Ta med egna prototyper och experiment för speltest

Kom gärna med egna önskemål och idéer så försöker vi få till det!
