* Praktisk info
- Plats: Spelinkubatorn, Lindholmen
- Tid: Kl 19 - 21, onsdagar.
- Start: 7 september

* Upplägg
- Varje tillfälle börjar med en liten presentation av de spel vi ska studera (oftast 3 - 5 st)
- Deltagarna delar upp sig och försöker hinna spela alla spel (de flesta kommer vara rätt korta)
- Vill man experimentera med egna regelvariationer eller nya spel uppmuntras detta
- Mot slutet samlas vi och diskuterar våra upplevelser, styrkor/svagheter med spelen, etc, etc.

* Planerade tillfällen

** Ett halvt ark papper
Spel som endast kräver papper och penna.

** Kort, kort, kort
Ovanliga spel med en vanlig kortlek.

** Schackbräde utan Schack
Ett gäng underliga spel som spelas på 8 x 8 rutor.

** För eremiten
Brädspel och kortspel som spelas ensam, mot spelet.

** Digital kartong
Vi tittar närmare på ett gäng brädspel designade specifikt för lokal multiplayer på iPad (ej digitala portningar av befintliga spel).


* Möjliga teman för framtiden

** Rollspel från 2000-talet
T.ex. Fiasco

** Twine

** Tärningsspel

Kom gärna med egna önskemål och idéer så försöker vi få till det!
